# fly.toml app configuration file generated for headd on 2025-02-23T10:56:54-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'headd'
primary_region = 'ewr'

# [env]
# GODEBUG = "http2debug=2"


[[services]]
internal_port = 7402
protocol = "tcp"
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
ports = [
  { port = 443, handlers = [
    "tls",
    "http",
  ] },
  { handlers = [
    "http",
  ], port = 80, force_https = true },
]
http_checks = [
  { interval = 10000, grace_period = "5s", method = "get", path = "/", protocol = "http", timeout = 2000, tls_skip_verify = false },
]

[[services]]
internal_port = 7401
protocol = "tcp"
ports = [{ port = 7401 }]

[[services]]
internal_port = 7400
protocol = "udp"
ports = [{ port = 7400 }]


[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
