// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type App struct {
	ID        int64
	Name      string
	User      string
	Meta      string
	CreatedAt string
}

type Host struct {
	ID        int64
	User      string
	Hostname  string
	CreatedAt string
}
