CREATE TABLE IF NOT EXISTS hosts (
    id INTEGER PRIMARY KEY,
    user TEXT NOT NULL,
    hostname TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
) STRICT;


CREATE TABLE IF NOT EXISTS app (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    user TEXT NOT NULL,
    meta TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
) STRICT;

