//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for BuildStatus.
const (
	Completed BuildStatus = "completed"
	Failed    BuildStatus = "failed"
	Pending   BuildStatus = "pending"
	Running   BuildStatus = "running"
)

// Defines values for HostStatus.
const (
	Offline HostStatus = "offline"
	Online  HostStatus = "online"
)

// Build Represents a build job and its status
type Build struct {
	Args        []string           `json:"args"`
	Command     string             `json:"command"`
	CompletedAt time.Time          `json:"completedAt"`
	CreatedAt   time.Time          `json:"createdAt"`
	Env         *map[string]string `json:"env,omitempty"`

	// ExitCode Process exit code when build completes
	ExitCode *int        `json:"exitCode,omitempty"`
	Id       string      `json:"id"`
	Status   BuildStatus `json:"status"`
	Stream   *bool       `json:"stream,omitempty"`
}

// BuildStatus defines model for Build.Status.
type BuildStatus string

// BuildRequest Request parameters to start a new build
type BuildRequest struct {
	Args    []string           `json:"args"`
	Command string             `json:"command"`
	Env     *map[string]string `json:"env,omitempty"`
	Stream  *bool              `json:"stream,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Host Represents a build host in the system
type Host struct {
	Id     string      `json:"id"`
	Name   string      `json:"name"`
	Status *HostStatus `json:"status,omitempty"`
}

// HostStatus defines model for Host.Status.
type HostStatus string

// BadRequestError defines model for BadRequestError.
type BadRequestError = Error

// NotFoundError defines model for NotFoundError.
type NotFoundError = Error

// PostHostsHostIdBuildJSONRequestBody defines body for PostHostsHostIdBuild for application/json ContentType.
type PostHostsHostIdBuildJSONRequestBody = BuildRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetHosts request
	GetHosts(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostHostsHostIdBuildWithBody request with any body
	PostHostsHostIdBuildWithBody(ctx context.Context, hostId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostHostsHostIdBuild(ctx context.Context, hostId string, body PostHostsHostIdBuildJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHostsHostIdBuildBuildId request
	GetHostsHostIdBuildBuildId(ctx context.Context, hostId string, buildId string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetHosts(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHostsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostHostsHostIdBuildWithBody(ctx context.Context, hostId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostHostsHostIdBuildRequestWithBody(c.Server, hostId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostHostsHostIdBuild(ctx context.Context, hostId string, body PostHostsHostIdBuildJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostHostsHostIdBuildRequest(c.Server, hostId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHostsHostIdBuildBuildId(ctx context.Context, hostId string, buildId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHostsHostIdBuildBuildIdRequest(c.Server, hostId, buildId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetHostsRequest generates requests for GetHosts
func NewGetHostsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hosts")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostHostsHostIdBuildRequest calls the generic PostHostsHostIdBuild builder with application/json body
func NewPostHostsHostIdBuildRequest(server string, hostId string, body PostHostsHostIdBuildJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostHostsHostIdBuildRequestWithBody(server, hostId, "application/json", bodyReader)
}

// NewPostHostsHostIdBuildRequestWithBody generates requests for PostHostsHostIdBuild with any type of body
func NewPostHostsHostIdBuildRequestWithBody(server string, hostId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hostId", runtime.ParamLocationPath, hostId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hosts/%s/build", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetHostsHostIdBuildBuildIdRequest generates requests for GetHostsHostIdBuildBuildId
func NewGetHostsHostIdBuildBuildIdRequest(server string, hostId string, buildId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hostId", runtime.ParamLocationPath, hostId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "buildId", runtime.ParamLocationPath, buildId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hosts/%s/build/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetHostsWithResponse request
	GetHostsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHostsResponse, error)

	// PostHostsHostIdBuildWithBodyWithResponse request with any body
	PostHostsHostIdBuildWithBodyWithResponse(ctx context.Context, hostId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostHostsHostIdBuildResponse, error)

	PostHostsHostIdBuildWithResponse(ctx context.Context, hostId string, body PostHostsHostIdBuildJSONRequestBody, reqEditors ...RequestEditorFn) (*PostHostsHostIdBuildResponse, error)

	// GetHostsHostIdBuildBuildIdWithResponse request
	GetHostsHostIdBuildBuildIdWithResponse(ctx context.Context, hostId string, buildId string, reqEditors ...RequestEditorFn) (*GetHostsHostIdBuildBuildIdResponse, error)
}

type GetHostsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Host
}

// Status returns HTTPResponse.Status
func (r GetHostsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHostsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostHostsHostIdBuildResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Build
	JSON400      *BadRequestError
	JSON404      *NotFoundError
}

// Status returns HTTPResponse.Status
func (r PostHostsHostIdBuildResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostHostsHostIdBuildResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHostsHostIdBuildBuildIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Build
	JSON404      *NotFoundError
}

// Status returns HTTPResponse.Status
func (r GetHostsHostIdBuildBuildIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHostsHostIdBuildBuildIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetHostsWithResponse request returning *GetHostsResponse
func (c *ClientWithResponses) GetHostsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHostsResponse, error) {
	rsp, err := c.GetHosts(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHostsResponse(rsp)
}

// PostHostsHostIdBuildWithBodyWithResponse request with arbitrary body returning *PostHostsHostIdBuildResponse
func (c *ClientWithResponses) PostHostsHostIdBuildWithBodyWithResponse(ctx context.Context, hostId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostHostsHostIdBuildResponse, error) {
	rsp, err := c.PostHostsHostIdBuildWithBody(ctx, hostId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostHostsHostIdBuildResponse(rsp)
}

func (c *ClientWithResponses) PostHostsHostIdBuildWithResponse(ctx context.Context, hostId string, body PostHostsHostIdBuildJSONRequestBody, reqEditors ...RequestEditorFn) (*PostHostsHostIdBuildResponse, error) {
	rsp, err := c.PostHostsHostIdBuild(ctx, hostId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostHostsHostIdBuildResponse(rsp)
}

// GetHostsHostIdBuildBuildIdWithResponse request returning *GetHostsHostIdBuildBuildIdResponse
func (c *ClientWithResponses) GetHostsHostIdBuildBuildIdWithResponse(ctx context.Context, hostId string, buildId string, reqEditors ...RequestEditorFn) (*GetHostsHostIdBuildBuildIdResponse, error) {
	rsp, err := c.GetHostsHostIdBuildBuildId(ctx, hostId, buildId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHostsHostIdBuildBuildIdResponse(rsp)
}

// ParseGetHostsResponse parses an HTTP response from a GetHostsWithResponse call
func ParseGetHostsResponse(rsp *http.Response) (*GetHostsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHostsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Host
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostHostsHostIdBuildResponse parses an HTTP response from a PostHostsHostIdBuildWithResponse call
func ParsePostHostsHostIdBuildResponse(rsp *http.Response) (*PostHostsHostIdBuildResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostHostsHostIdBuildResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Build
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequestError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetHostsHostIdBuildBuildIdResponse parses an HTTP response from a GetHostsHostIdBuildBuildIdWithResponse call
func ParseGetHostsHostIdBuildBuildIdResponse(rsp *http.Response) (*GetHostsHostIdBuildBuildIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHostsHostIdBuildBuildIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Build
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List available hosts
	// (GET /hosts)
	GetHosts(w http.ResponseWriter, r *http.Request)
	// Start a new build
	// (POST /hosts/{hostId}/build)
	PostHostsHostIdBuild(w http.ResponseWriter, r *http.Request, hostId string)
	// Get build status
	// (GET /hosts/{hostId}/build/{buildId})
	GetHostsHostIdBuildBuildId(w http.ResponseWriter, r *http.Request, hostId string, buildId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHosts operation middleware
func (siw *ServerInterfaceWrapper) GetHosts(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHosts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostHostsHostIdBuild operation middleware
func (siw *ServerInterfaceWrapper) PostHostsHostIdBuild(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "hostId" -------------
	var hostId string

	err = runtime.BindStyledParameterWithOptions("simple", "hostId", r.PathValue("hostId"), &hostId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hostId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostHostsHostIdBuild(w, r, hostId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHostsHostIdBuildBuildId operation middleware
func (siw *ServerInterfaceWrapper) GetHostsHostIdBuildBuildId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "hostId" -------------
	var hostId string

	err = runtime.BindStyledParameterWithOptions("simple", "hostId", r.PathValue("hostId"), &hostId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hostId", Err: err})
		return
	}

	// ------------- Path parameter "buildId" -------------
	var buildId string

	err = runtime.BindStyledParameterWithOptions("simple", "buildId", r.PathValue("buildId"), &buildId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "buildId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHostsHostIdBuildBuildId(w, r, hostId, buildId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/hosts", wrapper.GetHosts)
	m.HandleFunc("POST "+options.BaseURL+"/hosts/{hostId}/build", wrapper.PostHostsHostIdBuild)
	m.HandleFunc("GET "+options.BaseURL+"/hosts/{hostId}/build/{buildId}", wrapper.GetHostsHostIdBuildBuildId)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xWX2/bNhD/KsRtj1qVbn3SWzJsjYFhMNrHwA9n8WQzkEiNPKUzDH334UhZsSxlbeCm",
	"T6LE+/u7393pCKVrWmfJcoDiCJ5C62yg+HKH+hP901HgP7x3Xj6VzjJZliO2bW1KZONs/hiclW+h3FOD",
	"cvrZUwUF/JQ/28/TbciTtb7vM9AUSm9aMQIFrOwT1kYrn7xCn8Hfjv90ndU/KIJPFFznS1LWsarEMYjQ",
	"oBdB6Uyt5XCp2HoK4kSh2oqMenRbhVYrw0EFRu4CZNB615JnkxBGv4tPw9TEAx9aggICe2N3kv/wAb3H",
	"g7yXrmnQ6kVZSbQmJn0b4amcb5ChAI1Mv7BpCLIFJU/4ShWyTzF4rY1kj/V6ktRLObjtI5WxqPSv4d+d",
	"pjmMa+9KCkGJhCqdJvVlT3YA9JRfeA7KWKYdeTFqlkEZkC+OQLZroHiAlqyWywx8Z206jdBBBhWamjRs",
	"siVjnrA587N1ria0kSTCWuNJiw+j4blWWarzGMs56NOqbRbAioQb+nCJd/FCteixISYfFDuhm2eFytKX",
	"hN0bM+9qRnwzsBeYLgE2joppxg2FgDtaiOfCxUlwyfa9Wy7CrPn3LrAyVvGeVDgEpmZWghcIa7Ghb2Sy",
	"s7Wx0qKuquJpztklXkYP8+zEBZWdN3z4LPMuRbkl9ORvO96P4zXWJ35+bsQ9c5sGqrGVm0N0u16pynnV",
	"oMWdsTu1J0wohTgkI2qxsQ3XYvBe7m/XK8jgiXxIVt6/u3l3I1i4liy2Bgr4LX7KoEXex4DzaFROO4q1",
	"EszjklhpKOAj8X0UyKbL7tebm1etl7Fx/m/PRLrMemm+dv4ygZWrEh6TSkDxMK3Bw6bfZBC6pkF/OKni",
	"E5oatzUNFjJglP5+gPS+EZMJmPwoj5Xu8+1pk7UDqadArV1ISN1H+bvTGBkHTQzNSPiC/YlXBST7cE48",
	"9h1lZ+BdknSThCnwndOH77bmJ6Ozn/aChNTPOPD++/peqnW8SBOatJDjQ2LekrExuvzyXyzqffi63vT/",
	"6VXM+rywRKa0ymBo25f5lR/jY6X7r3bkGc/uks5b0S1bNLQdnb6SuFdMkesYJOvgCiKMlf5IPKyt8Q/l",
	"5UL3/X8BAAD//yj6a841DAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
